spring.application.name=weatherandgo

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/weatherandgo?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
spring.datasource.username=weathergo_user
spring.datasource.password=weathergo_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

openweather.api.key=62b7291d0f9f8fd0c8904838ee8502fd

recommendation.engine.base-url=http://localhost:8001